Repository coala/community, pull requests merged in 2018-05, with the labels that each got.

#130 .travis.yml: Enable travis-buddy
  .travis.yml
Labels: process/approved, size/XS

#128 Add: Unassigned issue app
  community/urls.py
  templates/index.html
  unassigned_issues/unassigned_issues_scraper.py
Labels: process/pending review, size/XS

#112 Move code out of command *.py for data app
  data/contrib_data.py
  data/management/commands/import_contributors_data.py
  data/migrations/0001_initial.py
Labels: process/approved, size/S
