Repository coala/community, pull requests merged in 2018-10, with the labels that each got.

#188 Corrected the typo in update.py
  gamification/process/update.py
Labels: difficulty/newcomer, in progress, process/pending review, size/XS

#183 Add support for Django 2.x
  gsoc/models.py
  meta_review/models.py
  requirements.txt
Labels: area/ci, process/pending review, size/XS

#208 settings.py: Add stderr logging of warnings
  community/settings.py
Labels: process/pending review, size/XS

#206 GCI18 task uploader
  .moban.yaml
  gci/api_actions.py
  gci/config.py
  gci/issues.py
  gci/management/commands/create_issue_tasks.py
  gci/management/commands/publish_tasks.py
  requirements.txt
Labels: area/ci, difficulty/low, difficulty/medium, importance/critical, process/pending review, size/L

#217 .moban.yaml: Disable openhub module
  .ci/build.sh
  .moban.yaml
  setup.cfg
Labels: process/approved, size/XS
