Repository coala/community, pull requests merged in 2018-06, with the labels that each got.

#134 Set up meta_review app
  community/settings.py
  community/urls.py
  meta_review/__init__.py
  meta_review/apps.py
  meta_review/migrations/0001_initial.py
  meta_review/migrations/__init__.py
  meta_review/models.py
  meta_review/urls.py
  meta_review/views.py
  templates/index.html
  templates/meta_review.html
Labels: enhancement, process/approved, size/M

#149 data/tests/: Add tests for data app
  .ci/build.sh
  data/tests/__init__.py
  data/tests/test_management_commands.py
  data/tests/test_models.py
  data/tests/test_views.py
Labels: process/approved, size/S

#147 fetch_deployed_data.py: Move to data app
  data/management/commands/fetch_deployed_data.py
Labels: area/ci, process/pending review, size/XS

#146 .travis.yml: Restructure env keys
  .coafile
  .travis.yml
Labels: process/pending review, size/XS

#157 .gitignore: Ignore prof directory
  .gitignore
Labels: area/ci, process/approved, size/XS
