Repository coala/community, pull requests merged in 2018-04, with the labels that each got.

#119 Fix broken travis on master
  requirements.txt
Labels: process/pending review, size/XS

#125 openhub/models.py: Fix str method
  openhub/models.py
Labels: difficulty/low, enhancement, importance/high, process/approved, size/XS

#121 README.md: Add netlify deploy instruction
  README.md
Labels: process/approved, size/XS

#115 Use Generic ListView
  community/settings.py
  community/urls.py
  model/__init__.py
  model/apps.py
  model/migrations/__init__.py
  model/urls.py
  model/views.py
  openhub/models.py
  templates/contributors.html
  templates/index.html
  templates/model.html
  templates/model/templates/affiliated_committer_detail.html
  templates/model/templates/affiliated_committer_list.html
  templates/model/templates/base.html
  templates/model/templates/organization_detail.html
  templates/model/templates/organization_list.html
  templates/model/templates/outside_committer_detail.html
  templates/model/templates/outside_committer_list.html
  templates/model/templates/outside_project_detail.html
  templates/model/templates/outside_project_list.html
  templates/model/templates/portfolio_project_detail.html
  templates/model/templates/portfolio_project_list.html
  templates/openhub.html
Labels: difficulty/medium, importance/medium, process/approved, size/L
