Repository coala/community, pull requests merged in 2018-03, with the labels that each got.

#86 ci: Use correct Python version specification
  runtime.txt
Labels: bug, difficulty/low, process/approved, size/XS

#73 Add pyflakes checking
  .coafile
  activity/scraper.py
  gci/management/commands/cleanse_gci_task_data.py
  gci/students.py
  gci/views.py
Labels: difficulty/low, difficulty/medium, initiatives/gci, process/approved, size/XS, status/STALE

#70 Import coala.io contributors functionality
  .ci/build.sh
  community/settings.py
  community/urls.py
  data/__init__.py
  data/apps.py
  data/management/commands/import_contributors_data.py
  data/migrations/0001_initial.py
  data/migrations/__init__.py
  data/models.py
  data/urls.py
  data/views.py
  db.sqlite3
  templates/contributors.html
  templates/index.html
Labels: difficulty/medium, importance/high, process/pending review, size/S

#96 .travis.yml: Enable pip caching
  .travis.yml
Labels: process/approved, size/XS

#98 Remove db.sqlite3
  .gitignore
  db.sqlite3
Labels: difficulty/low, importance/high, process/approved, size/XS

#103 Add: Inactive Issues app
  community/urls.py
  inactive_issues/inactive_issues_scraper.py
  requirements.txt
  templates/index.html
Labels: process/approved, size/XS

#109 .coafile: Fix spelling mistake
  .coafile
  inactive_issues/inactive_issues_scraper.py
Labels: process/approved, size/XS

#110 Webservices data errors
  data/management/commands/import_contributors_data.py
  data/models.py
Labels: bug, process/approved, size/XS

#105 .coafile: Check all shell scripts
  .ci/deploy.sh
  .coafile
Labels: difficulty/low, difficulty/medium, process/approved, size/XS

#77 Import OpenHub data
  .ci/build.sh
  .gitignore
  community/settings.py
  community/urls.py
  openhub/__init__.py
  openhub/affiliated_committers.py
  openhub/apps.py
  openhub/data.py
  openhub/management/commands/import_affiliated_committers_data.py
  openhub/management/commands/import_openhub_data.py
  openhub/management/commands/import_organization_data.py
  openhub/management/commands/import_outside_committers_data.py
  openhub/management/commands/import_outside_projects_data.py
  openhub/management/commands/import_portfolio_projects_data.py
  openhub/migrations/0001_initial.py
  openhub/migrations/__init__.py
  openhub/models.py
  openhub/oh_token.py
  openhub/organization.py
  openhub/outside_committers.py
  openhub/outside_projects.py
  openhub/portfolio_projects.py
  openhub/urls.py
  openhub/views.py
  requirements.txt
  templates/index.html
  templates/openhub.html
Labels: difficulty/medium, importance/medium, process/approved, size/L
