Repository coala/community, pull requests merged in 2018-07, with the labels that each got.

#158 gci: Fix GitHub cards failing to render
  gci/views.py
Labels: bug, process/approved, size/XS

#162 Sync gitignore list
  .gitignore
Labels: bug, process/approved, size/XS

#164 .coafile: Add PyPluralNamingBear
  .coafile
  gci/students.py
  inactive_issues/inactive_issues_scraper.py
  openhub/data.py
  test-requirements.txt
Labels: bug, enhancement, process/approved, size/XS

#166 Change meta-review models
  meta_review/migrations/0002_auto_20180707_0305.py
  meta_review/models.py
  meta_review/views.py
  templates/meta_review.html
Labels: process/approved, size/XS

#169 data/: Fix import_contributors_data command
  data/management/commands/import_contributors_data.py
Labels: bug, process/wip, size/XS

#143 Implement meta-review scoring & ranking system
  .ci/build.sh
  community/git.py
  data/management/commands/fetch_deployed_data.py
  meta_review/dump_to_db.py
  meta_review/handler.py
  meta_review/load_from_db.py
  meta_review/management/commands/run_meta_review_system.py
Labels: area/ci, enhancement, process/approved, size/L

#138 Add teams to Contributor model
  data/contrib_data.py
  data/migrations/0002_auto_20180704_1130.py
  data/models.py
  data/webservices.py
  templates/contributors.html
Labels: process/pending review, size/XS
