Repository coala/community, pull requests merged in 2018-08, with the labels that each got.

#100 Import IGitt Data
  .ci/build.sh
  data/issues.py
  data/management/commands/import_issues_data.py
  data/management/commands/import_merge_requests_data.py
  data/merge_requests.py
  data/migrations/0003_auto_20180801_0456.py
  data/models.py
  data/newcomers.py
  data/tests/test_management_commands.py
  data/tests/test_models.py
Labels: difficulty/low, difficulty/medium, enhancement, process/approved, size/L

#170 Gitorg.py: Remove unused variable
  gci/gitorg.py
Labels: area/ci, bug, difficulty/newcomer, enhancement, process/approved, size/XS, type/style

#174 setup.cfg: Use template
  .ci/build.sh
  .coafile
  .moban.dt/community-test-requirements.txt.jj2
  .moban.yaml
  .nocover.yaml
  .travis.yml
  conftest.py
  setup.cfg
  test-requirements.txt
Labels: process/approved, size/M

#178 test-requirements.txt: Sync
  test-requirements.txt
Labels: process/pending review, size/XS

#177 Get 100% test coverage for data app
  .nocover.yaml
  data/tests/test_contrib_data.py
  data/tests/test_issues.py
  data/tests/test_merge_requests.py
  setup.cfg
Labels: process/wip, size/XS
